ALTER TABLE `question_sets`
  ADD COLUMN `exam_kind` VARCHAR(20) NOT NULL DEFAULT 'mock',
  ADD COLUMN `total_questions` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `duration_seconds` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `price` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `is_free` TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN `display_order` INTEGER NOT NULL DEFAULT 0;
